### ISSUE TITLE
Pickles used to train HAST-IDS

### ISSUE THREAD

**Issue by Clapperclaws** [echowei/DeepTraffic#15]
Can you please share the sessions and labels pickles? or the code you used to generate them from the pcaps.

**Comment by echowei** [comment]
Sorry, I planned to compile all the intermediate code and data and add github together, but the time after work cannot be guaranteed and the plan has not been completed so far.
Suggestion: After using the pkt2flow tool to split the file, use the xml tag file as the standard to find the corresponding stream file according to the 4-tuples. Due to the difference in the split mechanism, the two results are different in number and cannot be matched one by one.

**Comment by jsilaa** [comment]
Dear Dr Wei Wang,

Can you kindly advice me where to locate file? 
DATA_DIR = '/root/data/****_PreprocessedISCX2012_5class_pkl_**/'**

Thank you in advance
